<a href="https://colab.research.google.com/github/abdullahzahid10/EEEM066/blob/main/Lab2p2_Unfinished.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Start by import the necessary libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [3]:
# Creating a scalar in PyTorch
scalar = torch.tensor(10)
scalar

tensor(10)

In [4]:
# Dimension of this scalar
scalar.ndim

0

In [5]:
# Create a 1 dimensional vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# the shape of the vector is NOT the mathematical dimensionality of it
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [8]:
# Create a 2x2 matrix
m = torch.tensor([[7, 8],
                       [9, 10]])
m

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# confirm that this is a 2x2 square matirx
m.shape

torch.Size([2, 2])

In [10]:
m.ndim

2

In [11]:
m[1]

tensor([ 9, 10])

In [12]:
# The first column
m[:,0]

tensor([7, 9])

In [13]:
# Let's create a 3x3 Tensor
T=torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

T

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
T.ndim

3

In [15]:
T.shape

torch.Size([1, 3, 3])

In [16]:
T[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
T[1]

IndexError: ignored

In [19]:
random_tensor = torch.rand(3, 4) # this will return a tensor filled with random numbers from a uniform distribution on the interval  [0,1)

random_tensor

tensor([[0.7355, 0.9510, 0.3524, 0.8202],
        [0.2507, 0.0056, 0.4593, 0.2861],
        [0.1982, 0.1550, 0.6784, 0.3651]])

In [20]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
                                                        # When reading code from the internet, bear in mind C will be either
                                                        # the first or last entry in the the image tensor

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [ ]:
temp = np.array(5.0)
temp.dtype

In [27]:
random_tensor.dtype

torch.float32

In [26]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations, there's nothing to learn here, so it's set to 'False

float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # Explicitly instructing pytorch to create a float16 tensor
float_16_tensor

In [34]:
# What do you think the dtype of the outcome of this operation will be?
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
output = float_16_tensor * float_32_tensor
output.dtype

torch.float32

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [36]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

In [37]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0286, 0.6896, 0.7200, 0.9155],
        [0.9405, 0.8105, 0.5180, 0.5866],
        [0.5606, 0.2530, 0.3190, 0.4604]])

In [38]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0286, 0.6896, 0.7200, 0.9155],
        [0.9405, 0.8105, 0.5180, 0.5866],
        [0.5606, 0.2530, 0.3190, 0.4604]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [39]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multiply tensor by 10
mult = tensor * 10
mult

tensor([10, 20, 30])

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
# Substract 10
subt = tensor - 10
subt

tensor([-9, -8, -7])

In [43]:
# Try out PyTorch in-built functions (whenever you can, use these!)
# Note the use of the assert statment: https://realpython.com/python-assert-statement/
# Note the use of the Pytorch built-in torch.sum function
mult2 = torch.mul(tensor, 10)
assert torch.sum(mult) == torch.sum(mult2)

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [45]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
tensor2 = torch.Tensor([[2,3],[4,5]])
tensor3 = torch.Tensor([[1,4],[5,6]])
print(tensor2, "*", tensor3)
print(f"Equals: {tensor2 * tensor3}")

tensor([[2., 3.],
        [4., 5.]]) * tensor([[1., 4.],
        [5., 6.]])
Equals: tensor([[ 2., 12.],
        [20., 30.]])


In [47]:
torch.matmul(tensor, tensor)

tensor(14)

In [48]:
1*1 + 2*2 + 3*3

14

In [49]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 2.29 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.27 ms, sys: 40 µs, total: 1.31 ms
Wall time: 1.14 ms


tensor(14)