In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

# create a 2-dimensional NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr1[0])      # prints 1
print(arr2[1, 2])   # prints 6
print(arr2[:, 1])

1
6
[2 5 8]


In [ ]:
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
arr_uint16 = np.array([10, 20, 30], dtype=np.uint16)

print(arr_int8.dtype)   # output: int8
print(arr_uint16.dtype) # output: uint16

int8
uint16


In [ ]:
arr_float32 = np.array([1.0, 2.5, 3.7], dtype=np.float32)
arr_complex128 = np.array([1 + 2j, 3 + 4j], dtype=np.complex128)

print(arr_float32.dtype)      # output: float32
print(arr_complex128.dtype)   # output: complex128

float32
complex128


In [ ]:
arr_bool = np.array([True, False, True], dtype=np.bool)

print(arr_bool.dtype)    # output: bool


bool


<ipython-input-6-482b03fa2b97>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr_bool = np.array([True, False, True], dtype=np.bool)


In [ ]:

arr_string = np.array(['hello', 'world'], dtype=np.string_)
arr_unicode = np.array(['こんにちは', '안녕하세요'], dtype=np.unicode_)

print(arr_string.dtype)   # output: |S5 (5 bytes per string)
print(arr_unicode.dtype)  # output:

|S5
<U5


In [ ]:
#1. Broadcasting a scalar value to an array

arr = np.array([1, 2, 3])
scalar = 2

# multiply every element of arr by scalar
result = arr * scalar

print(result) # output: [2, 4, 6]

#scalar value 2 is broadcasted to the same shape as the arr array, which is [1, 2, 3]


[2 4 6]


In [ ]:
#2. Broadcasting a one-dimensional array to a two-dimensional array

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# add arr1 to every row of arr2
result = arr1 + arr2

print(result)
# output: [[2, 4, 6], [5, 7, 9]]
# arr1 is broadcasted to the same shape as each row of the arr2 array, which is [1, 2, 3].

[[2 4 6]
 [5 7 9]]


In [ ]:

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# add arr2 to every column of arr1
result = arr1 + arr2

print(result)
# output: [[11, 22, 33], [14, 25, 36]]
#  arr2 is broadcasted to the same shape as each column of the arr1 array, which is [[10, 20, 30

[[11 22 33]
 [14 25 36]]


In [ ]:
#reshape a 1D array to a 2D array using the following code:

# create a 1D array with 9 elements
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# reshape the array to a 3x3 matrix
b = a.reshape((3, 3))

print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

# create a 2D array
a = np.array([[1, 2], [3, 4]])

# transpose the array
b = a.transpose()

print(b)

[[1 3]
 [2 4]]


In [ ]:
# create a 2D array
a = np.array([[1, 2], [3, 4]])

# flatten the array
b = a.flatten()

print(b)


[1 2 3 4]


In [ ]:


# create a 1D array with 3 elements
a = np.array([1, 2, 3])

# add a new dimension to create a 2D array
b = a[np.newaxis, :]

print(b)


[[1 2 3]]
