<a href="https://colab.research.google.com/github/abdullahzahid10/EEEM066/blob/main/Lab2p2_Unfinished.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Start by import the necessary libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
# Creating a scalar in PyTorch
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
# Dimension of this scalar
scalar.ndim

0

In [ ]:
# Create a 1 dimensional vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# the shape of the vector is NOT the mathematical dimensionality of it
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
# Create a 2x2 matrix
m = torch.tensor([[7, 8],
                       [9, 10]])
m

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# confirm that this is a 2x2 square matirx
m.shape

torch.Size([2, 2])

In [ ]:
m.ndim

2

In [ ]:
m[1]

tensor([ 9, 10])

In [ ]:
# The first column
m[:,0]

tensor([7, 9])

In [ ]:
# Let's create a 3x3 Tensor
T=torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

T

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
T.ndim

3

In [ ]:
T.shape

torch.Size([1, 3, 3])

In [ ]:
T[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
T[1]

IndexError: ignored

In [ ]:
random_tensor = torch.rand(3, 4) # this will return a tensor filled with random numbers from a uniform distribution on the interval  [0,1)

random_tensor

tensor([[0.2317, 0.5646, 0.9622, 0.6935],
        [0.0742, 0.6360, 0.2090, 0.9938],
        [0.2660, 0.7269, 0.1747, 0.2165]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
                                                        # When reading code from the internet, bear in mind C will be either
                                                        # the first or last entry in the the image tensor

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
temp = np.array(5.0)
temp.dtype

dtype('float64')

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations, there's nothing to learn here, so it's set to 'False

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # Explicitly instructing pytorch to create a float16 tensor
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# What do you think the dtype of the outcome of this operation will be?
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
output = float_16_tensor * float_32_tensor
output.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])